//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScholarshipContractService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Scholarship", Namespace="http://schemas.datacontract.org/2004/07/SMS_Service.Model")]
    public partial class Scholarship : object
    {
        
        private double AmountField;
        
        private System.DateTime DeadlineField;
        
        private string DescriptionField;
        
        private ScholarshipContractService.StudentEducation EducationField;
        
        private System.Nullable<double> GPARequirementField;
        
        private int IDField;
        
        private bool IsDeletedField;
        
        private System.Nullable<int> MaxAgeField;
        
        private System.Nullable<int> MinAgeField;
        
        private string NameField;
        
        private ScholarshipContractService.ScholarshipApplication[] ScholarshipApplicationsField;
        
        private System.Nullable<int> StudentLimitField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Deadline
        {
            get
            {
                return this.DeadlineField;
            }
            set
            {
                this.DeadlineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ScholarshipContractService.StudentEducation Education
        {
            get
            {
                return this.EducationField;
            }
            set
            {
                this.EducationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> GPARequirement
        {
            get
            {
                return this.GPARequirementField;
            }
            set
            {
                this.GPARequirementField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted
        {
            get
            {
                return this.IsDeletedField;
            }
            set
            {
                this.IsDeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxAge
        {
            get
            {
                return this.MaxAgeField;
            }
            set
            {
                this.MaxAgeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MinAge
        {
            get
            {
                return this.MinAgeField;
            }
            set
            {
                this.MinAgeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ScholarshipContractService.ScholarshipApplication[] ScholarshipApplications
        {
            get
            {
                return this.ScholarshipApplicationsField;
            }
            set
            {
                this.ScholarshipApplicationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StudentLimit
        {
            get
            {
                return this.StudentLimitField;
            }
            set
            {
                this.StudentLimitField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentEducation", Namespace="http://schemas.datacontract.org/2004/07/SMS_Service.Model")]
    public enum StudentEducation : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HighSchool = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        University = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScholarshipApplication", Namespace="http://schemas.datacontract.org/2004/07/SMS_Service.Model")]
    public partial class ScholarshipApplication : object
    {
        
        private System.Nullable<System.DateTime> ApprovalDateField;
        
        private int IDField;
        
        private int ScholarshipIdField;
        
        private ScholarshipContractService.ScholarshipApplicationStatus StatusField;
        
        private int StudentIdField;
        
        private System.DateTime SubmissionDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ApprovalDate
        {
            get
            {
                return this.ApprovalDateField;
            }
            set
            {
                this.ApprovalDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ScholarshipId
        {
            get
            {
                return this.ScholarshipIdField;
            }
            set
            {
                this.ScholarshipIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ScholarshipContractService.ScholarshipApplicationStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId
        {
            get
            {
                return this.StudentIdField;
            }
            set
            {
                this.StudentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SubmissionDate
        {
            get
            {
                return this.SubmissionDateField;
            }
            set
            {
                this.SubmissionDateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScholarshipApplicationStatus", Namespace="http://schemas.datacontract.org/2004/07/SMS_Service.Model")]
    public enum ScholarshipApplicationStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ScholarshipContractService.IScholarshipContract")]
    public interface IScholarshipContract
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScholarshipContract/Create", ReplyAction="http://tempuri.org/IScholarshipContract/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(ScholarshipContractService.Scholarship scholarship);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScholarshipContract/Update", ReplyAction="http://tempuri.org/IScholarshipContract/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(ScholarshipContractService.Scholarship scholarship);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScholarshipContract/Delete", ReplyAction="http://tempuri.org/IScholarshipContract/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScholarshipContract/GetAll", ReplyAction="http://tempuri.org/IScholarshipContract/GetAllResponse")]
        System.Threading.Tasks.Task<ScholarshipContractService.Scholarship[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScholarshipContract/GetById", ReplyAction="http://tempuri.org/IScholarshipContract/GetByIdResponse")]
        System.Threading.Tasks.Task<ScholarshipContractService.Scholarship> GetByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IScholarshipContractChannel : ScholarshipContractService.IScholarshipContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ScholarshipContractClient : System.ServiceModel.ClientBase<ScholarshipContractService.IScholarshipContract>, ScholarshipContractService.IScholarshipContract
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ScholarshipContractClient() : 
                base(ScholarshipContractClient.GetDefaultBinding(), ScholarshipContractClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IScholarshipContract.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ScholarshipContractClient(EndpointConfiguration endpointConfiguration) : 
                base(ScholarshipContractClient.GetBindingForEndpoint(endpointConfiguration), ScholarshipContractClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ScholarshipContractClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ScholarshipContractClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ScholarshipContractClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ScholarshipContractClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ScholarshipContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task CreateAsync(ScholarshipContractService.Scholarship scholarship)
        {
            return base.Channel.CreateAsync(scholarship);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(ScholarshipContractService.Scholarship scholarship)
        {
            return base.Channel.UpdateAsync(scholarship);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id)
        {
            return base.Channel.DeleteAsync(id);
        }
        
        public System.Threading.Tasks.Task<ScholarshipContractService.Scholarship[]> GetAllAsync()
        {
            return base.Channel.GetAllAsync();
        }
        
        public System.Threading.Tasks.Task<ScholarshipContractService.Scholarship> GetByIdAsync(int id)
        {
            return base.Channel.GetByIdAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IScholarshipContract))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IScholarshipContract))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:54087/ScholarshipService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ScholarshipContractClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IScholarshipContract);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ScholarshipContractClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IScholarshipContract);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IScholarshipContract,
        }
    }
}
