//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentContractService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/SMS_Service.Model")]
    public partial class Student : object
    {
        
        private string DateOfBirthField;
        
        private StudentContractService.StudentEducation EducationField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private double GPAField;
        
        private int IDField;
        
        private bool IsDeletedField;
        
        private string LastNameField;
        
        private StudentContractService.ScholarshipApplication[] ScholarshipApplicationsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateOfBirth
        {
            get
            {
                return this.DateOfBirthField;
            }
            set
            {
                this.DateOfBirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentContractService.StudentEducation Education
        {
            get
            {
                return this.EducationField;
            }
            set
            {
                this.EducationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double GPA
        {
            get
            {
                return this.GPAField;
            }
            set
            {
                this.GPAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted
        {
            get
            {
                return this.IsDeletedField;
            }
            set
            {
                this.IsDeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentContractService.ScholarshipApplication[] ScholarshipApplications
        {
            get
            {
                return this.ScholarshipApplicationsField;
            }
            set
            {
                this.ScholarshipApplicationsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentEducation", Namespace="http://schemas.datacontract.org/2004/07/SMS_Service.Model")]
    public enum StudentEducation : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HighSchool = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        University = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScholarshipApplication", Namespace="http://schemas.datacontract.org/2004/07/SMS_Service.Model")]
    public partial class ScholarshipApplication : object
    {
        
        private System.Nullable<System.DateTime> ApprovalDateField;
        
        private int IDField;
        
        private int ScholarshipIdField;
        
        private StudentContractService.ScholarshipApplicationStatus StatusField;
        
        private int StudentIdField;
        
        private System.DateTime SubmissionDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ApprovalDate
        {
            get
            {
                return this.ApprovalDateField;
            }
            set
            {
                this.ApprovalDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ScholarshipId
        {
            get
            {
                return this.ScholarshipIdField;
            }
            set
            {
                this.ScholarshipIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentContractService.ScholarshipApplicationStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId
        {
            get
            {
                return this.StudentIdField;
            }
            set
            {
                this.StudentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SubmissionDate
        {
            get
            {
                return this.SubmissionDateField;
            }
            set
            {
                this.SubmissionDateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScholarshipApplicationStatus", Namespace="http://schemas.datacontract.org/2004/07/SMS_Service.Model")]
    public enum ScholarshipApplicationStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentContractService.IStudentContract")]
    public interface IStudentContract
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentContract/Create", ReplyAction="http://tempuri.org/IStudentContract/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(StudentContractService.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentContract/Update", ReplyAction="http://tempuri.org/IStudentContract/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(StudentContractService.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentContract/Delete", ReplyAction="http://tempuri.org/IStudentContract/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentContract/GetAll", ReplyAction="http://tempuri.org/IStudentContract/GetAllResponse")]
        System.Threading.Tasks.Task<StudentContractService.Student[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentContract/GetById", ReplyAction="http://tempuri.org/IStudentContract/GetByIdResponse")]
        System.Threading.Tasks.Task<StudentContractService.Student> GetByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IStudentContractChannel : StudentContractService.IStudentContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class StudentContractClient : System.ServiceModel.ClientBase<StudentContractService.IStudentContract>, StudentContractService.IStudentContract
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public StudentContractClient() : 
                base(StudentContractClient.GetDefaultBinding(), StudentContractClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IStudentContract.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StudentContractClient(EndpointConfiguration endpointConfiguration) : 
                base(StudentContractClient.GetBindingForEndpoint(endpointConfiguration), StudentContractClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StudentContractClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(StudentContractClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StudentContractClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(StudentContractClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StudentContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task CreateAsync(StudentContractService.Student student)
        {
            return base.Channel.CreateAsync(student);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(StudentContractService.Student student)
        {
            return base.Channel.UpdateAsync(student);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id)
        {
            return base.Channel.DeleteAsync(id);
        }
        
        public System.Threading.Tasks.Task<StudentContractService.Student[]> GetAllAsync()
        {
            return base.Channel.GetAllAsync();
        }
        
        public System.Threading.Tasks.Task<StudentContractService.Student> GetByIdAsync(int id)
        {
            return base.Channel.GetByIdAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IStudentContract))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IStudentContract))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:54087/StudentService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return StudentContractClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IStudentContract);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return StudentContractClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IStudentContract);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IStudentContract,
        }
    }
}
